config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'masuk_ke_website_bimas_katolik_sumba_tengah', to: 'devise/sessions#new'
    get 'mendaftar_ke_website_bimas_katolik_sumba_tengah', to: 'devise/registrations#new'
  end

  resources :arsip

  root to: 'web#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arsip.rb
class Arsip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arsip_controller.rb
class ArsipController < ApplicationController
  before_action :set_arsip, only: [:show, :edit, :update, :destroy]

  # GET /arsip
  # GET /arsip.json
  def index
    @arsip = Arsip.all
  end

  # GET /arsip/1
  # GET /arsip/1.json
  def show
  end

  # GET /arsip/new
  def new
    @arsip = Arsip.new
  end

  # GET /arsip/1/edit
  def edit
  end

  # POST /arsip
  # POST /arsip.json
  def create
    @arsip = Arsip.new(arsip_params)

    respond_to do |format|
      if @arsip.save
        format.html { redirect_to @arsip, notice: 'Arsip was successfully created.' }
        format.json { render :show, status: :created, location: @arsip }
      else
        format.html { render :new }
        format.json { render json: @arsip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arsip/1
  # PATCH/PUT /arsip/1.json
  def update
    respond_to do |format|
      if @arsip.update(arsip_params)
        format.html { redirect_to @arsip, notice: 'Arsip was successfully updated.' }
        format.json { render :show, status: :ok, location: @arsip }
      else
        format.html { render :edit }
        format.json { render json: @arsip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arsip/1
  # DELETE /arsip/1.json
  def destroy
    @arsip.destroy
    respond_to do |format|
      format.html { redirect_to arsip_index_url, notice: 'Arsip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arsip
      @arsip = Arsip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arsip_params
      params.require(:arsip).permit(:judul, :keterangan)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :nama,
                                  :email,
                                  :password,
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :nama, 
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end
end

app/controllers/web_controller.rb
class WebController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
end

app/helpers/arsip_helper.rb
module ArsipHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

end

app/helpers/web_helper.rb
module WebHelper
end

app/views/arsip/_form.html.erb
<%= form_with(model: arsip, local: true) do |form| %>
  <% if arsip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arsip.errors.count, "error") %> prohibited this arsip from being saved:</h2>

      <ul>
      <% arsip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :judul %>
    <%= form.text_field :judul %>
  </div>

  <div class="field">
    <%= form.label :keterangan %>
    <%= form.text_area :keterangan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arsip/edit.html.erb
<h1>Editing Arsip</h1>

<%= render 'form', arsip: @arsip %>

<%= link_to 'Show', @arsip %> |
<%= link_to 'Back', arsip_index_path %>

app/views/arsip/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arsip</h1>

<table>
  <thead>
    <tr>
      <th>Judul</th>
      <th>Keterangan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arsip.each do |arsip| %>
      <tr>
        <td><%= arsip.judul %></td>
        <td><%= arsip.keterangan %></td>
        <td><%= link_to 'Show', arsip %></td>
        <td><%= link_to 'Edit', edit_arsip_path(arsip) %></td>
        <td><%= link_to 'Destroy', arsip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arsip', new_arsip_path %>

app/views/arsip/new.html.erb
<h1>New Arsip</h1>

<%= render 'form', arsip: @arsip %>

<%= link_to 'Back', arsip_index_path %>

app/views/arsip/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Judul:</strong>
  <%= @arsip.judul %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @arsip.keterangan %>
</p>

<%= link_to 'Edit', edit_arsip_path(@arsip) %> |
<%= link_to 'Back', arsip_index_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
  <%= render 'layouts/navigation/header' %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BimasKatolik</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item dropdown active">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Tentang
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/tentang/visi_misi">Visi dan Misi Kantor Kementerian Agama Kabupaten Sumba Tengah</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="/tentang/tekad_urakat">Tekad Pelayanan Seksi Urusan Agama Katolik</a>
        <a class="dropdown-item" href="/tentang/tekad_pendakat">Tekad Pelayanan Penyelenggara Pendidikan Agama Katolik</a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Data
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/data/keagamaan_katolik">Data Keagamaan Katolik</a>
        <a class="dropdown-item" href="/data/pendidikan_katolik">Data Pendidikan Agama Katolik</a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Galeri
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/galeri/foto">Foto</a>
        <a class="dropdown-item" href="/galeri/video">Video</a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Informasi
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/informasi/berita_terkini">Berita Terkini</a>
        <a class="dropdown-item" href="/informasi/pengumuman">Pengumuman</a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Laporan
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/laporan/penyuluh_agama_katolik">Laporan Penyuluh Agama Katolik</a>
        <a class="dropdown-item" href="/laporan/kinerja_pegawai_bimkat_sumteng">Laporan Kinerja Pegawai Bimkat Sumteng</a>
      </div>
    </li>

  </ul>

      <%= render collapsible_links_partial_path %>

</div>

app/views/layouts/navigation/_header.html.erb
<%= link_to 'Bimkat Sumteng', root_path, class: 'navbar-brand' %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<%= render 'layouts/navigation/collapsible_elements' %>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<form class="form-inline my-2 my-lg-0">
  <button class="btn btn-outline-primary my-2 my-sm-0" href="/laporan/penyuluh_agama_katolik">Masuk</button>
  <button class="btn btn-outline-success my-2 my-sm-0" href="/laporan/penyuluh_agama_katolik">Mendaftar</button>
</form>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span id="user-name"><%= current_user.nama %></span>
    <span class="caret"></span>
  </a>

  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
  </div>
</li>

app/views/web/index.html.erb
<h1>Selamat Datang,</h1>
<p>saat ini Anda berada di Website Bimas Katolik Kantor Kementerian Agama Kabupaten Sumba Tengah. Untuk memulai, Anda dapat memilih salah satu dari menu yang tersedia.</p>
<p>Salve!</p>